version: "3.4"

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=kanrule
      - POSTGRES_PASSWORD=kanrule
      - POSTGRES_DB=kanrule
    networks:
      - kanrule
    volumes:
      - ./persist/db/git:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - 9090:3000
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=kanrule
      - DB_PASSWORD=kanrule
      - DB_DATABASE=kanrule
      ## Please change this string to something unique.
      - JWT_SECRET=development12345
    command: ["api"]
    depends_on:
      - db
    networks:
      - kanrule

  client:
    build: .
    restart: always
    environment:
    ports:
      - 8080:8080
    networks:
      - kanrule
    environment:
      - RUN_MODE=api
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=kanrule
      - DB_PASSWORD=kanrule
      - DB_DATABASE=kanrule
      ## Please change this string to something unique.
      - JWT_SECRET=development12345
    depends_on:
      - api
    command: ["client"]

networks:
  kanrule:
